pipeline{
    agent any
    stages{
        stage('checkout'){
            steps{
                git branch: 'DJango-application', url:'https://github.com/DeepikaVKale/reimagined-journey.git'
            }
        }
        stage('Docker image build'){
            steps{
                sh'''
                cd ecommerce 
                docker build -t deepikavkale/django-application:1 . 
                '''
            }
        }
        stage('Containerisation'){
            steps{
                sh'''
                docker stop c-django
                docker rm c-django
                docker run -it -d --name c-django -p 8000:8000 deepikavkale/django-application:1
                ''' 
            }
        }
        stage('Login to Docker Hub'){
            steps{
                script{
                    withCredentials ([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')])
                    {
                        sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                    }
                }
            }
        }
        stage('Pushing image to repository'){
            steps{
                sh 'docker push deepikavkale/django-application:1'
            }
        }
    }
}
